# Generated by Django 5.2.5 on 2025-09-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('nome_setor', models.CharField(max_length=255)),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('média', 'Média'), ('alta', 'Alta')], default='baixa', max_length=10)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('a fazer', 'A fazer'), ('fazendo', 'Fazendo'), ('pronto', 'Pronto')], default='a fazer', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
