# Generated by Django 5.2.5 on 2025-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tarefa_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('a fazer', 'A fazer'), ('fazendo', 'Fazendo'), ('concluido', 'Concluido')], default='a fazer', max_length=10),
        ),
    ]
